"""
heightmap2map.py
Heightmap → NetRadiant Brush Prefab Generator
Requires: PyQt6, Pillow
Install:  pip install PyQt6 Pillow
"""

import sys
import os
import math
from datetime import datetime

from PyQt6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QPushButton, QFileDialog, QSpinBox, QDoubleSpinBox,
    QLineEdit, QCheckBox, QGroupBox, QGridLayout, QTextEdit,
    QSizePolicy, QSplitter, QFrame, QProgressBar, QComboBox
)
from PyQt6.QtGui import QPixmap, QImage, QPainter, QColor, QPen, QFont
from PyQt6.QtCore import Qt, QThread, pyqtSignal, QRect

try:
    from PIL import Image
    import struct
except ImportError:
    print("Missing dependency: pip install Pillow")
    sys.exit(1)


# ─── Worker thread ────────────────────────────────────────────────────────────

class GeneratorWorker(QThread):
    progress = pyqtSignal(int)
    log      = pyqtSignal(str)
    finished = pyqtSignal(str)  # emits the .map string

    def __init__(self, params):
        super().__init__()
        self.p = params

    def run(self):
        p = self.p
        img: Image.Image = p['image'].convert('L')  # greyscale
        if p['invert']:
            from PIL import ImageOps
            img = ImageOps.invert(img)

        iw, ih = img.size
        res     = p['resolution']
        terrW   = p['terrain_w']
        terrD   = p['terrain_d']
        maxH    = p['max_height']
        floorH  = p['floor_height']
        tex     = p['texture']
        topTex  = p['top_texture'] or tex
        wrapEnt = p['wrap_entity']
        uvs     = '0 0 0 1 1'

        cellW = terrW / res
        cellD = terrD / res
        ox    = -terrW / 2.0
        oz    = -terrD / 2.0

        pixels = img.load()

        def sample(nx, ny):
            """Bilinear sample, returns 0.0–1.0"""
            px = nx * (iw - 1)
            py = ny * (ih - 1)
            x0, y0 = int(px), int(py)
            x1, y1 = min(x0 + 1, iw - 1), min(y0 + 1, ih - 1)
            fx, fy = px - x0, py - y0
            def g(x, y): return pixels[x, y] / 255.0
            return (g(x0,y0)*(1-fx)*(1-fy) +
                    g(x1,y0)*fx*(1-fy)     +
                    g(x0,y1)*(1-fx)*fy     +
                    g(x1,y1)*fx*fy)

        def fmt_pt(x, y, z):
            return f"( {x:.2f} {y:.2f} {z:.2f} )"

        def plane(p1, p2, p3, t=tex):
            return f"{fmt_pt(*p1)} {fmt_pt(*p2)} {fmt_pt(*p3)} {t} {uvs}"

        def make_tri_brush(A, B, C, zbot):
            Ab = (A[0], A[1], zbot)
            Bb = (B[0], B[1], zbot)
            Cb = (C[0], C[1], zbot)
            lines = [
                plane(A, C, B, topTex),   # sloped top face
                plane(Ab, Bb, Cb),         # flat bottom
                plane(A, B, Bb),           # side AB
                plane(B, C, Cb),           # side BC
                plane(C, A, Ab),           # side CA
            ]
            return '{\n' + '\n'.join(lines) + '\n}'

        brushes = []
        total   = res * res
        zbot    = -floorH

        self.log.emit(f"Generating {res}×{res} grid → {total*2} brushes…")

        for gy in range(res):
            for gx in range(res):
                h00 = sample( gx      / res,  gy      / res) * maxH
                h10 = sample((gx + 1) / res,  gy      / res) * maxH
                h01 = sample( gx      / res, (gy + 1) / res) * maxH
                h11 = sample((gx + 1) / res, (gy + 1) / res) * maxH

                x0 = ox + gx       * cellW
                x1 = ox + (gx + 1) * cellW
                y0 = oz + gy       * cellD
                y1 = oz + (gy + 1) * cellD

                A = (x0, y0, h00)
                B = (x1, y0, h10)
                C = (x1, y1, h11)
                D = (x0, y1, h01)

                brushes.append(make_tri_brush(A, B, C, zbot))
                brushes.append(make_tri_brush(A, C, D, zbot))

            pct = int((gy + 1) / res * 90)
            self.progress.emit(pct)

        self.log.emit(f"Assembling .map file ({len(brushes)} brushes)…")

        lines = [
            f'// Generated by heightmap2map.py — {datetime.now().strftime("%Y-%m-%d %H:%M")}',
            f'// Terrain: {terrW}×{terrD} units, max height {maxH}, resolution {res}×{res}',
            '',
        ]

        if wrapEnt:
            lines.append('{')
            lines.append('"classname" "func_group"')
            lines.append('"_type" "terrain"')
            lines.extend(brushes)
            lines.append('}')
        else:
            lines.append('{')
            lines.append('"classname" "worldspawn"')
            lines.extend(brushes)
            lines.append('}')

        output = '\n'.join(lines) + '\n'
        self.progress.emit(100)
        self.log.emit(f"Done. {len(brushes)} brushes, {len(output)//1024}kb")
        self.finished.emit(output)


# ─── Heightmap Preview Widget ─────────────────────────────────────────────────

class HeightmapView(QLabel):
    def __init__(self):
        super().__init__()
        self.setMinimumSize(300, 300)
        self.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setStyleSheet("background:#111; border:1px solid #333;")
        self.setText("No image loaded")
        self._pil_image = None
        self._resolution = 32

    def set_image(self, pil_img, resolution=32):
        self._pil_image = pil_img.convert('L')
        self._resolution = resolution
        self._render()

    def set_resolution(self, res):
        self._resolution = res
        if self._pil_image:
            self._render()

    def _render(self):
        if not self._pil_image:
            return
        img = self._pil_image
        res = self._resolution
        w = self.width() or 300
        h = self.height() or 300
        sz = min(w, h)

        qimg = QImage(sz, sz, QImage.Format.Format_RGB32)
        qimg.fill(QColor(10, 10, 10))
        painter = QPainter(qimg)

        cell = sz / res
        iw, ih = img.size
        pixels = img.load()

        for gy in range(res):
            for gx in range(res):
                nx = (gx + 0.5) / res
                ny = (gy + 0.5) / res
                px = int(nx * (iw - 1))
                py = int(ny * (ih - 1))
                val = pixels[px, py] / 255.0

                r = int(val * val * 200)
                g = int(60 + val * 180)
                b = int(20 + (1 - val) * 80)
                painter.fillRect(
                    QRect(int(gx*cell), int(gy*cell), math.ceil(cell)+1, math.ceil(cell)+1),
                    QColor(r, g, b)
                )

        painter.end()
        self.setPixmap(QPixmap.fromImage(qimg))

    def resizeEvent(self, event):
        super().resizeEvent(event)
        if self._pil_image:
            self._render()


# ─── Main Window ──────────────────────────────────────────────────────────────

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Heightmap → NetRadiant Brush Prefab Generator")
        self.setMinimumSize(900, 620)
        self._image     = None
        self._map_str   = None
        self._worker    = None
        self._build_ui()

    def _build_ui(self):
        central = QWidget()
        self.setCentralWidget(central)
        root = QHBoxLayout(central)
        root.setContentsMargins(10, 10, 10, 10)
        root.setSpacing(10)

        splitter = QSplitter(Qt.Orientation.Horizontal)
        root.addWidget(splitter)

        # ── Left panel ──────────────────────────────────────
        left = QWidget()
        left.setMaximumWidth(340)
        lv = QVBoxLayout(left)
        lv.setSpacing(8)

        # Image load
        img_grp = QGroupBox("Heightmap Image")
        ig = QVBoxLayout(img_grp)
        self.img_label = QLabel("No image loaded")
        self.img_label.setStyleSheet("color:#888; font-size:11px;")
        self.img_label.setWordWrap(True)
        ig.addWidget(self.img_label)
        btn_load = QPushButton("Browse…")
        btn_load.clicked.connect(self._load_image)
        ig.addWidget(btn_load)
        lv.addWidget(img_grp)

        # Terrain scale
        scale_grp = QGroupBox("Terrain Scale")
        sg = QGridLayout(scale_grp)

        sg.addWidget(QLabel("Grid Resolution:"), 0, 0)
        self.spin_res = QSpinBox()
        self.spin_res.setRange(4, 128)
        self.spin_res.setValue(32)
        self.spin_res.setSingleStep(4)
        self.spin_res.setToolTip("Number of cells per axis. 32×32 = 2048 brushes.")
        self.spin_res.valueChanged.connect(self._on_res_change)
        sg.addWidget(self.spin_res, 0, 1)

        sg.addWidget(QLabel("Width (X units):"), 1, 0)
        self.spin_w = QDoubleSpinBox()
        self.spin_w.setRange(64, 65536)
        self.spin_w.setValue(1024)
        self.spin_w.setSingleStep(64)
        sg.addWidget(self.spin_w, 1, 1)

        sg.addWidget(QLabel("Depth (Y units):"), 2, 0)
        self.spin_d = QDoubleSpinBox()
        self.spin_d.setRange(64, 65536)
        self.spin_d.setValue(1024)
        self.spin_d.setSingleStep(64)
        sg.addWidget(self.spin_d, 2, 1)

        sg.addWidget(QLabel("Max Height (Z):"), 3, 0)
        self.spin_h = QDoubleSpinBox()
        self.spin_h.setRange(8, 8192)
        self.spin_h.setValue(256)
        self.spin_h.setSingleStep(16)
        sg.addWidget(self.spin_h, 3, 1)

        sg.addWidget(QLabel("Floor Thickness:"), 4, 0)
        self.spin_floor = QDoubleSpinBox()
        self.spin_floor.setRange(1, 256)
        self.spin_floor.setValue(16)
        self.spin_floor.setSingleStep(4)
        self.spin_floor.setToolTip("Minimum brush thickness below terrain surface.")
        sg.addWidget(self.spin_floor, 4, 1)

        lv.addWidget(scale_grp)

        # Brush options
        brush_grp = QGroupBox("Brush Options")
        bg = QVBoxLayout(brush_grp)

        bg.addWidget(QLabel("Side/Bottom Texture:"))
        self.edit_tex = QLineEdit("textures/common/terrain")
        bg.addWidget(self.edit_tex)

        bg.addWidget(QLabel("Top Face Texture:"))
        self.edit_top_tex = QLineEdit("textures/base_floor/clangdark")
        bg.addWidget(self.edit_top_tex)

        self.chk_entity = QCheckBox("Wrap in func_group entity")
        self.chk_entity.setChecked(True)
        bg.addWidget(self.chk_entity)

        self.chk_invert = QCheckBox("Invert heightmap (dark = high)")
        bg.addWidget(self.chk_invert)

        lv.addWidget(brush_grp)

        # Generate / Save buttons
        self.btn_generate = QPushButton("Generate .MAP")
        self.btn_generate.setEnabled(False)
        self.btn_generate.setFixedHeight(36)
        font = self.btn_generate.font()
        font.setBold(True)
        self.btn_generate.setFont(font)
        self.btn_generate.clicked.connect(self._generate)
        lv.addWidget(self.btn_generate)

        self.btn_save = QPushButton("Save terrain.map…")
        self.btn_save.setEnabled(False)
        self.btn_save.clicked.connect(self._save)
        lv.addWidget(self.btn_save)

        self.progress = QProgressBar()
        self.progress.setVisible(False)
        lv.addWidget(self.progress)

        lv.addStretch()
        splitter.addWidget(left)

        # ── Right panel ──────────────────────────────────────
        right = QWidget()
        rv = QVBoxLayout(right)
        rv.setSpacing(8)

        rv.addWidget(QLabel("Heightmap Preview (colourised by height):"))
        self.preview = HeightmapView()
        rv.addWidget(self.preview, stretch=1)

        rv.addWidget(QLabel("Log:"))
        self.log = QTextEdit()
        self.log.setReadOnly(True)
        self.log.setMaximumHeight(120)
        self.log.setStyleSheet("background:#0a0a0a; color:#aaa; font-family:monospace; font-size:11px;")
        rv.addWidget(self.log)

        splitter.addWidget(right)
        splitter.setSizes([340, 560])

    # ── Slots ────────────────────────────────────────────────────────────────

    def _load_image(self):
        path, _ = QFileDialog.getOpenFileName(
            self, "Open Heightmap", "",
            "Images (*.png *.jpg *.jpeg *.bmp *.tga *.tiff *.exr)"
        )
        if not path:
            return
        try:
            self._image = Image.open(path)
            name = os.path.basename(path)
            w, h = self._image.size
            self.img_label.setText(f"{name}\n{w}×{h} px")
            self.btn_generate.setEnabled(True)
            self.preview.set_image(self._image, self.spin_res.value())
            self._log(f"Loaded: {name} ({w}×{h})")
        except Exception as e:
            self._log(f"Error loading image: {e}")

    def _on_res_change(self, val):
        if self._image:
            self.preview.set_resolution(val)

    def _generate(self):
        if not self._image:
            return

        self.btn_generate.setEnabled(False)
        self.btn_save.setEnabled(False)
        self.progress.setVisible(True)
        self.progress.setValue(0)

        params = {
            'image':       self._image,
            'resolution':  self.spin_res.value(),
            'terrain_w':   self.spin_w.value(),
            'terrain_d':   self.spin_d.value(),
            'max_height':  self.spin_h.value(),
            'floor_height':self.spin_floor.value(),
            'texture':     self.edit_tex.text().strip() or 'textures/common/terrain',
            'top_texture': self.edit_top_tex.text().strip(),
            'wrap_entity': self.chk_entity.isChecked(),
            'invert':      self.chk_invert.isChecked(),
        }

        self._worker = GeneratorWorker(params)
        self._worker.progress.connect(self.progress.setValue)
        self._worker.log.connect(self._log)
        self._worker.finished.connect(self._on_done)
        self._worker.start()

    def _on_done(self, map_str):
        self._map_str = map_str
        self.btn_generate.setEnabled(True)
        self.btn_save.setEnabled(True)
        self.progress.setVisible(False)

    def _save(self):
        if not self._map_str:
            return
        path, _ = QFileDialog.getSaveFileName(
            self, "Save .MAP file", "terrain.map", "Quake MAP files (*.map)"
        )
        if not path:
            return
        try:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(self._map_str)
            self._log(f"Saved: {path}")
        except Exception as e:
            self._log(f"Save error: {e}")

    def _log(self, msg):
        self.log.append(msg)


# ─── Entry point ──────────────────────────────────────────────────────────────

def main():
    app = QApplication(sys.argv)
    app.setStyle('Fusion')
    win = MainWindow()
    win.show()
    sys.exit(app.exec())


if __name__ == '__main__':
    main()